-- 나이 컬럼
ALTER TABLE APP_USERS ADD AGE NUMBER(3);

-- 범위 체크 (DB 차단)
ALTER TABLE APP_USERS ADD CONSTRAINT CK_USERS_HEIGHT CHECK (HEIGHT_CM IS NULL OR (HEIGHT_CM BETWEEN 100 AND 400));
ALTER TABLE APP_USERS ADD CONSTRAINT CK_USERS_WEIGHT CHECK (WEIGHT_KG IS NULL OR (WEIGHT_KG BETWEEN 15 AND 500));
ALTER TABLE APP_USERS ADD CONSTRAINT CK_USERS_AGE    CHECK (AGE IS NULL OR (AGE BETWEEN 10 AND 120));
