server:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: c##idev
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      "[hibernate.format_sql]": true
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

app:
  cors:
    allowed-origins:
      - "http://localhost:*"
      - "http://127.0.0.1:*"
  jwt:
    secret: ${JWT_SECRET:change-me}
    access-exp-min: 180
  ai:
    mode: mock
    ollama:
      base-url: http://localhost:11434
      model: llama3

external:
  clarifai:
    api-key: ${CLARIFAI_API_KEY:}
    model-id: food-item-recognition
  usda:
    api-key: ${USDA_API_KEY:}
